// Mock processes for the wave-1 firms and the investment banks (wave 2). Stage order, names and timings follow lib/firms/<firm>.ts and the research in
// docs/research/03-firm-processes-wave1.md. Where the research found conflicts or no source, the stage says so in `note`.
// Reported interview questions come from the firm profiles (paraphrased candidate reports, each with its own source);
// the rest are original questions written against the firm's own values or behaviours.

import { FIRMS } from "@/lib/firms";
import {
  BAKERY_CASE,
  DELOITTE_TOPICS,
  ENGINE_CASE,
  GS_REASONING,
  GYM_CASE,
  HSBC_EMAIL,
  LLOYDS_EMAIL,
  MARKETS_STORY,
  PITCH_60,
  RECYCLING_CASE,
  RETAIL_BANK_CASE,
  RR_PRESENTATION,
  SETTLEMENT_CASE,
} from "./cases";
import { autoMock } from "./auto";
import type { MockProcess, MockStage, QaPrompt } from "./types";

const firm = (slug: string) => {
  const f = FIRMS.find((x) => x.slug === slug);
  if (!f) throw new Error(`Unknown firm ${slug}`);
  return f;
};

/** Strip research annotations ("Note: ...", parenthetical remarks about the source) so a prompt reads as the question alone. */
export function cleanQuestion(q: string): string {
  return q
    .replace(/\s*\(BrightStart\)\s*$/, "")
    .replace(/\s*Note:[\s\S]*$/, "")
    .replace(/\s*\((?:the |reported|candidate|single)[^)]*\)/gi, "")
    .trim();
}

/** Reported questions for a firm, kept only if they read as a single standalone question. */
function reported(slug: string, stage: RegExp, max = 6, maxLen = 230): QaPrompt[] {
  return firm(slug)
    .questions.filter((q) => stage.test(q.stage) && q.question.length < maxLen && !/^(Reported in|Common questions)/.test(q.question) && !/\(reported/.test(q.question))
    .slice(0, max)
    .map((q) => ({ text: cleanQuestion(q.question) }));
}

const prompts = (...texts: string[]): QaPrompt[] => texts.map((text) => ({ text }));

const framework = (slug: string, name: string, take?: number) => ({ name, items: firm(slug).values.slice(0, take) });

const APPLICATION = (stageOrder: number, summary: string, tips: string[]): MockStage => ({
  kind: "info",
  name: "Online application",
  stageOrder,
  summary,
  tips,
});

const NOT_REPLICATED = (name: string, stageOrder: number, summary: string, note: string): MockStage => ({
  kind: "info",
  name,
  stageOrder,
  summary,
  tips: ["This stage is not simulated here. Read the firm guide for what to expect and how to prepare."],
  note,
});

export const MOCKS: MockProcess[] = [
  {
    firm: "pwc",
    title: "PwC mock process",
    confidence: "multiple-candidate-reports",
    framework: framework("pwc", "The PwC Professional"),
    notes: [
      "PwC is the least certain profile: PwC's pages could not be read directly and sources conflict on stages, video format and assessment-centre length. Treat the order and timings as approximate and follow your invitation.",
    ],
    stages: [
      APPLICATION(1, "An online form with your details and qualifications. Flying Start programmes are also applied for through UCAS, and you can only make one application per cycle.", [
        "Be specific to the programme if there are motivation questions.",
        "Check you meet the university offer as well as PwC's process (Flying Start).",
      ]),
      { kind: "test", name: "Immersive job preview (situational judgement)", testId: "sjt-most-least", stageOrder: 2, note: "PwC's page describes about 15 short video scenarios; this replica uses written scenarios." },
      { kind: "test", name: "Psychometric questionnaire", testId: "work-style-forced-choice", stageOrder: 2, note: "PwC's current list includes a games-based assessment, which is not replicated; other reports describe a behavioural questionnaire and SHL cognitive tests. This stands in for the questionnaire part." },
      {
        kind: "qa",
        name: "On-demand video interview",
        mode: "video",
        stageOrder: 3,
        intro: "Questions appear on screen, and you record your answers. Reports of the format conflict (30 seconds to 3 minutes of preparation, 2 to 3 minutes to answer, 3 to 10 questions): this uses 30 seconds and 2 minutes.",
        prepSeconds: 30,
        answerSeconds: 120,
        retakes: 0,
        prompts: [
          ...reported("pwc", /Video interview/),
          ...prompts(
            "Describe a time you worked with other people to get something done at school, work or in a club. What was your part?",
            "Tell me about a time you had to learn something new quickly.",
            "Tell me about a time you saw a better way to do something and what you did about it.",
            "How do you make sure you get on with people who think differently from you?",
          ),
        ],
        note: "Question count, preparation time and retakes conflict across sources.",
      },
      {
        kind: "qa",
        name: "Virtual assessment centre: case study",
        mode: "exercise",
        stageOrder: 4,
        intro: "Candidates report case-study tasks involving data and short written recommendations. Read the case, prepare, then give your recommendation. The real agenda for 2026/27 is not confirmed.",
        prepSeconds: 600,
        answerSeconds: 360,
        retakes: 0,
        prompts: [{ text: BAKERY_CASE.brief, stimulus: BAKERY_CASE.stimulus }],
        note: "Assessment-centre length and activities conflict across sources; group exercises are not simulated.",
      },
      {
        kind: "qa",
        name: "Final interview",
        mode: "interview",
        stageOrder: 5,
        intro: "A competency interview with a senior leader from your business area. This stage is not confirmed in PwC's current five-stage list, so it is included as unconfirmed.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(
          "Why PwC, why this line of service, and why a route that combines work with study?",
          "Tell me about a time you built a good working relationship with someone.",
          "Tell me about a time you used data or evidence to make a decision.",
          "Pick a technology and describe how it has influenced the industries PwC works in.",
          "Tell me about a time you took responsibility for getting something right.",
        ),
        note: "Not in PwC's current five-stage excerpt: unconfirmed for 2026/27.",
      },
    ],
  },
  {
    firm: "deloitte",
    title: "Deloitte mock process",
    confidence: "official",
    framework: framework("deloitte", "Deloitte's five values"),
    notes: [
      "Based on Deloitte's own pages (five steps). Deloitte publishes no timings for the online assessment or job simulation, so those are approximate.",
    ],
    stages: [
      APPLICATION(1, "About 15 minutes: personal and educational details, submitted in one session. Deloitte allows one application per academic year.", [
        "Check eligibility (104 UCAS points for BrightStart) before you apply.",
      ]),
      { kind: "test", name: "Immersive assessment: ranking actions", testId: "sjt-ranking", stageOrder: 3, note: "Deloitte says you rank the most and least likely actions in workplace scenarios. Timings are not published." },
      { kind: "test", name: "Immersive assessment: numerical reasoning", testId: "capp-numerical", stageOrder: 3, note: "Deloitte includes numerical and verbal reasoning. Prep sites report Cappfinity runs it, so this uses a Cappfinity-style, time-recorded replica." },
      { kind: "test", name: "Immersive assessment: verbal reasoning", testId: "capp-verbal", stageOrder: 3 },
      { kind: "test", name: "Job simulation: inbox tasks", testId: "job-sim-audit", stageOrder: 4, note: "Deloitte's job simulation includes written and email tasks. This replica is an original audit inbox; Deloitte publishes no timings." },
      {
        kind: "qa",
        name: "Job simulation: recorded answers",
        mode: "video",
        stageOrder: 4,
        intro: "The job simulation includes video-recorded answers, reported at 30 seconds to 2 minutes each, alongside written and email tasks. Deloitte publishes no timings.",
        prepSeconds: 30,
        answerSeconds: 120,
        retakes: 0,
        prompts: prompts(
          "Tell us about a time you worked well with someone whose approach was different from yours.",
          "Describe a time you took the lead on something. What did you do and what happened?",
          "Why does this kind of work interest you, and what do you hope to learn in your first year?",
        ),
        note: "Preparation and answer times are single-report; the number of questions varies.",
      },
      {
        kind: "qa",
        name: "Final stage: topic discussion",
        mode: "exercise",
        stageOrder: 5,
        intro: "Deloitte sends four topics in advance; you prepare one and discuss it with an assessor for 30 to 40 minutes. In this mock you prepare for ten minutes and talk through your chosen topic.",
        prepSeconds: 600,
        answerSeconds: 240,
        retakes: 0,
        prompts: prompts(DELOITTE_TOPICS),
      },
      {
        kind: "qa",
        name: "Final stage: skills and motivation interview",
        mode: "interview",
        stageOrder: 5,
        intro: "About 50 minutes of competency, motivation, scenario and topical questions. This mock asks a selection of them.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: reported("deloitte", /Final stage/, 6),
      },
      { kind: "info", name: "Outcome", stageOrder: 6, summary: "Deloitte gives personalised feedback whatever the result.", tips: ["Use the feedback to improve, and reapply next academic year if unsuccessful."] },
    ],
  },
  {
    firm: "kpmg",
    title: "KPMG mock process",
    confidence: "official",
    framework: framework("kpmg", "KPMG's strengths"),
    notes: [
      "Based on KPMG's apprentice application page. The live provider, cognitive test item counts and video preparation time are not published.",
    ],
    stages: [
      APPLICATION(1, "About 45 minutes: a job preview quiz that is not assessed, then an application form.", ["Use the job preview to learn what the role involves day to day."]),
      { kind: "test", name: "Skills assessment (untimed, about 20 minutes)", testId: "work-style-rating", stageOrder: 2, note: "KPMG's skills assessment is untimed and about 20 minutes; this uses a work-style rating questionnaire as a stand-in." },
      { kind: "test", name: "Cognitive assessment: numerical (first half of 36 minutes)", testId: "shl-numerical", stageOrder: 2, note: "KPMG's cognitive assessment is 36 minutes covering numerical and logical reasoning; this splits it into two 18-minute replicas." },
      { kind: "test", name: "Cognitive assessment: logical (second half of 36 minutes)", testId: "shl-inductive", stageOrder: 2 },
      {
        kind: "qa",
        name: "Video interview (about 40 minutes)",
        mode: "video",
        stageOrder: 3,
        intro: "KPMG's video interview is six pre-recorded questions put by an AI avatar, with preparation time before each answer, and takes about 40 minutes. Topics: skills, experience and motivation.",
        prepSeconds: 30,
        answerSeconds: 120,
        retakes: 0,
        prompts: prompts(
          "Why are you interested in a career at KPMG and in this service line?",
          "Tell me about a time you had to be resilient.",
          "Tell me about a time you built a relationship with someone new.",
          "Describe a time you planned your time to meet a deadline.",
          "Tell me about a time you used critical thinking to solve a problem.",
          "What do you want to learn from an apprenticeship, and how will you make the most of it?",
        ),
        note: "Preparation and answer times for the apprentice version are not confirmed.",
      },
      {
        kind: "qa",
        name: "Launch Pad: analysis task",
        mode: "exercise",
        stageOrder: 4,
        intro: "Launch Pad is an in-person half day. Third-party sources report a group exercise, an analysis task and a senior interview. This stage replicates a short individual analysis task.",
        prepSeconds: 480,
        answerSeconds: 300,
        retakes: 0,
        prompts: [{ text: GYM_CASE.brief, stimulus: GYM_CASE.stimulus }],
        note: "The Launch Pad agenda is from third-party sources only; the group exercise is not simulated.",
      },
      {
        kind: "qa",
        name: "Launch Pad: senior interview",
        mode: "interview",
        stageOrder: 4,
        intro: "Reported at about 45 minutes, on motivation and scenarios.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: reported("kpmg", /Launch Pad/, 4),
        note: "Questions are from a single commercial prep page.",
      },
    ],
  },
  {
    firm: "ey",
    title: "EY mock process",
    confidence: "official",
    framework: framework("ey", "EY's strengths (list not confirmed on an official page)"),
    notes: [
      "Based on EY's process page and FAQ. Apprentices attend the Experience Day in person. Apprentice item counts and timings are not published, and the final interview is probably part of the Experience Day.",
    ],
    stages: [
      APPLICATION(1, "Create an account and complete the application form. Apprentices wait three months after a rejection before applying again.", ["Roles close once filled, so apply early."]),
      { kind: "test", name: "Online assessment: realistic job preview", testId: "sjt-ranking", stageOrder: 2, note: "EY describes rank-order questions on teamwork and learning capability. Counts and timings are not published." },
      { kind: "test", name: "Online assessment: numerical reasoning", testId: "capp-numerical", stageOrder: 2, note: "EY says some programmes include a numerical test. Prep sites report a single Cappfinity 'EY One Assessment' since 2025, so this uses a Cappfinity-style replica. Format and timing are not published." },
      {
        kind: "qa",
        name: "Online assessment: recorded video answers",
        mode: "video",
        stageOrder: 2,
        intro: "Recorded video answers are part of EY's online assessment. The number of questions and timings are not published.",
        prepSeconds: 30,
        answerSeconds: 120,
        retakes: 0,
        prompts: prompts(
          "Tell me about a time you worked as part of a team. What was your role?",
          "Why are you interested in a career at EY?",
          "Tell me about a time you had to adapt to something unexpected.",
        ),
        note: "Question count and timings are not published.",
      },
      {
        kind: "qa",
        name: "Experience Day: case study and presentation",
        mode: "exercise",
        stageOrder: 4,
        intro: "A single graduate-oriented report gives case preparation of 60 minutes, then a 15-minute presentation and 15 minutes of questions. This mock shortens the preparation to keep the session practical.",
        prepSeconds: 900,
        answerSeconds: 360,
        retakes: 0,
        prompts: [{ text: RECYCLING_CASE.brief, stimulus: RECYCLING_CASE.stimulus }],
        note: "Experience Day agenda is a single report and graduate-oriented; the group exercise is not simulated.",
      },
      {
        kind: "qa",
        name: "Experience Day: strengths and motivation interview",
        mode: "interview",
        stageOrder: 5,
        intro: "EY describes an interview on your strengths and motivations. Questions below combine reported ones with original ones.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: [...reported("ey", /Final interview/, 4), ...prompts("Tell me about a time you were curious enough to find something out for yourself.", "Tell me about a time you were accountable for something that did not go to plan.")],
      },
    ],
  },
  {
    firm: "barclays",
    title: "Barclays mock process",
    confidence: "official",
    framework: framework("barclays", "RISES", 5),
    notes: [
      "Based on Barclays' apprentice application journey page. The test vendor, item counts and whether the group activity runs are unconfirmed. Barclays says using third-party AI tools in an assessment or interview ends the application: do not use AI tools in the real process.",
    ],
    stages: [
      APPLICATION(1, "About 30 minutes: academic background and work experience, plus your CV. You can only apply once every six months.", ["Check the minimum entry criteria first and keep your login details."]),
      { kind: "test", name: "Initial assessment: interactive numerical", testId: "shl-numerical", stageOrder: 2, note: "Barclays describes two interactive assessments totalling about 60 minutes, completed within 5 days. Candidates report SHL-style numerical and personality content; Barclays does not name the vendor." },
      { kind: "test", name: "Initial assessment: preferred ways of working", testId: "work-style-rating", stageOrder: 2, note: "Barclays' wording is 'preferred ways of working'." },
      {
        kind: "qa",
        name: "Interview with leadership",
        mode: "interview",
        stageOrder: 3,
        intro: "A motivational interview with leadership, reported at about 70 minutes with mostly behavioural questions and a few about the role. This mock asks a selection.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: [
          ...reported("barclays", /Interview/, 4),
          ...prompts(
            "Tell me about a time you treated someone with respect when it would have been easier not to.",
            "Tell me about a time you put someone else's needs first.",
            "Tell me about a time you set a high standard for your own work.",
            "Tell me about a time you were honest when it was difficult.",
          ),
        ],
      },
      NOT_REPLICATED("Group activity", 3, "Barclays' page lists a group activity alongside the interview, but the only candidate report found described an interview with no group exercise.", "Whether the group activity runs is unconfirmed."),
      { kind: "info", name: "Offer or feedback", stageOrder: 4, summary: "Successful candidates move to pre-employment checks. Unsuccessful candidates receive a personalised feedback report and can reapply after six months.", tips: ["Use the feedback report if you reapply."] },
    ],
  },
  {
    firm: "rolls-royce",
    title: "Rolls-Royce mock process",
    confidence: "official",
    framework: framework("rolls-royce", "The four Rolls-Royce behaviours", 4),
    notes: [
      "Based on Rolls-Royce's published 2026 assessment-centre guide, which lists the interview questions and the 1 to 6 behaviour rating scale. The online assessment guide is from 2021/22, so those timings are approximate.",
    ],
    stages: [
      APPLICATION(1, "An application form followed by three short essay-style questions of roughly 300 words each (no CV).", ["Tie every example back to Rolls-Royce.", "Choose two topical issues you can defend at interview: the interview repeats this question."]),
      { kind: "test", name: "Online assessment: situational judgement exercise", testId: "sjt-most-least", stageOrder: 2, note: "Rolls-Royce describes a chat-style situational judgement exercise of up to about 15 minutes. This replica uses written scenarios." },
      { kind: "test", name: "Online assessment: work-style questionnaire", testId: "work-style-rating", stageOrder: 2, note: "The Measurement of Competencies questionnaire is untimed." },
      { kind: "test", name: "Online assessment: numerical and logical reasoning (about 6 minutes each)", testId: "scales-numerical", stageOrder: 2, note: "The 2021/22 guide gives about 6 minutes per reasoning test and the test ends when time is up. Role-specific tests vary." },
      {
        kind: "qa",
        name: "Assessment centre: interview",
        mode: "interview",
        stageOrder: 3,
        intro: "Degree apprentices attend in person. The guide publishes the interview questions (seven for degree apprentices), and assessors rate each behaviour from 1 to 6.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: reported("rolls-royce", /Assessment centre/, 7, 2000),
      },
      {
        kind: "qa",
        name: "Assessment centre: prepared presentation",
        mode: "exercise",
        stageOrder: 3,
        intro: "A seven-minute presentation on a technical subject, followed by short questions. In person there is no projector, so use notes or handouts.",
        prepSeconds: 300,
        answerSeconds: 420,
        retakes: 0,
        prompts: prompts(RR_PRESENTATION),
      },
      {
        kind: "qa",
        name: "Assessment centre: technical case study",
        mode: "exercise",
        stageOrder: 3,
        intro: "Degree and higher apprentices respond to a case study given on the day. The real content differs; this is an original engineering-style case.",
        prepSeconds: 600,
        answerSeconds: 300,
        retakes: 0,
        prompts: [{ text: ENGINE_CASE.brief, stimulus: ENGINE_CASE.stimulus }],
        note: "The real case-study content is not published.",
      },
      { kind: "info", name: "Offer and feedback", stageOrder: 4, summary: "A decision follows the assessment centre. Candidates report offers within about two weeks, and detailed feedback if unsuccessful.", tips: ["Ask for feedback if unsuccessful."] },
    ],
  },
  {
    firm: "bae-systems",
    title: "BAE Systems mock process",
    confidence: "official",
    framework: framework("bae-systems", "BAE Systems values and behaviours"),
    notes: [
      "BAE's page confirms three stages: application, a virtual assessment with gamified challenges and video questions, then an interview. Game names, video timings and the number of questions come only from single reports, and the games are not replicated.",
    ],
    stages: [
      APPLICATION(1, "A short form with your grades, work experience and interests. Qualifications are reviewed against the role criteria. Applications reopen in January 2027 for about six weeks.", ["Give full grades and relevant interests.", "Pick the business area that genuinely fits and say why."]),
      NOT_REPLICATED("Virtual assessment: gamified challenges", 2, "BAE says the virtual assessment includes gamified challenges. Candidates report a shape-matching game, a maths game and an image-choice game.", "Game names and formats are single-report and are not replicated here."),
      {
        kind: "qa",
        name: "Virtual assessment: video questions",
        mode: "video",
        stageOrder: 2,
        intro: "Candidates report 3 to 5 past-experience questions on a HireVue-style platform, with retakes mentioned. Preparation time conflicts across reports (30 seconds to 3 minutes): this uses 60 seconds.",
        prepSeconds: 60,
        answerSeconds: 120,
        retakes: 1,
        prompts: prompts(
          "Tell me about a time you had to make a decision with very little time.",
          "Why do you want to work for BAE Systems as an apprentice?",
          "Tell me about a time you met a requirement that was outside your comfort zone.",
          "Tell me about a time you worked well in a team.",
        ),
        note: "Number of questions, preparation time and retakes are single-report and conflict.",
      },
      {
        kind: "qa",
        name: "Interview",
        mode: "interview",
        stageOrder: 3,
        intro: "A virtual or face-to-face interview. Candidates report behavioural questions similar to the video round plus technical questions about the role.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: [...reported("bae-systems", /Interview/, 4), ...prompts("Tell me about a time you showed courage or did the right thing when it was difficult.")],
      },
      { kind: "info", name: "Offer and vetting", stageOrder: 4, summary: "Many roles need security vetting, and nationality or residency rules can apply. Check the live advert.", tips: [] },
    ],
  },
  {
    firm: "lloyds",
    title: "Lloyds Banking Group mock process",
    confidence: "official",
    framework: framework("lloyds", "Lloyds' values and behaviours"),
    notes: [
      "Lloyds' pages confirm three stages and that you may need a pen, paper and calculator. Test vendor, timings and the assessment-centre contents are not official and conflict across sources, so the final stage is approximate.",
    ],
    stages: [
      APPLICATION(1, "A form about yourself and your qualifications. Applications open on 3 November (the year is not stated). Those who meet the minimum criteria go to the assessments.", ["Check the minimum criteria for your specific apprenticeship."]),
      { kind: "test", name: "Online assessment: motivation, behaviours and values", testId: "work-style-rating", stageOrder: 2, note: "Lloyds describes assessments of motivations, behaviours and values. The format is not published." },
      { kind: "test", name: "Online assessment: situational judgement", testId: "sjt-most-least", stageOrder: 2, note: "A 2025 candidate report says the online test was scenario-based with nothing numerical for their route." },
      {
        kind: "qa",
        name: "Online assessment: written communication",
        mode: "exercise",
        stageOrder: 2,
        intro: "Lloyds says written communication is assessed. Write your answer as a reply to the customer.",
        prepSeconds: 0,
        answerSeconds: 600,
        retakes: 0,
        prompts: prompts(LLOYDS_EMAIL),
        note: "The real written task is not published.",
      },
      {
        kind: "qa",
        name: "Final stage: strengths-based interview",
        mode: "interview",
        stageOrder: 3,
        intro: "Candidates report a strengths-based interview: what you enjoy, what you are like at your best, and how you would put the customer first. The exact format varies by apprenticeship.",
        prepSeconds: 0,
        answerSeconds: 150,
        retakes: 0,
        prompts: [
          ...reported("lloyds", /Final interview/, 1),
          ...prompts(
            "What are you like when you are at your best?",
            "What do you enjoy doing, and why?",
            "Tell me about something you achieved and how you did it.",
            "How would you put the customer first in this role?",
            "What kind of tasks do you find draining, and how do you handle them?",
          ),
        ],
        note: "Strengths-based style is single-report.",
      },
      NOT_REPLICATED("Assessment day exercises", 3, "Reports mention micro-exercises, a group exercise and, for some routes, a virtual reality exercise. Contents conflict and none is official.", "Not replicated: contents are unconfirmed."),
    ],
  },
  {
    firm: "goldman-sachs",
    title: "Goldman Sachs mock process",
    confidence: "official",
    framework: framework("goldman-sachs", "Goldman Sachs' core values", 4),
    notes: [
      "Stages follow Goldman Sachs' own guidance: application, HireVue, then a Superday (Engineering applicants also take a HackerRank test). Question counts and timings for the HireVue come from candidate and prep-site reports.",
    ],
    stages: [
      APPLICATION(1, "An online form with your CV and grades. You choose a division (FICC and Equities, Engineering or Operations). Applications are processed in batches, so you may wait weeks for news.", [
        "Tailor your CV to the division you choose.",
        "Apply early even though replies can be slow.",
      ]),
      {
        kind: "qa",
        name: "HireVue video interview",
        mode: "video",
        stageOrder: 2,
        intro: "Goldman Sachs says the HireVue takes about 30 minutes. Candidates report 5 to 6 behavioural and motivational questions with 30 seconds to prepare, up to 2 minutes to answer and no retakes. FICC applicants report a more technical question.",
        prepSeconds: 30,
        answerSeconds: 120,
        retakes: 0,
        prompts: prompts(
          "Why Goldman Sachs specifically, rather than investment banking in general?",
          "Why have you chosen this division, and what do you think you would be doing day to day?",
          "Tell me about a time you worked in a team under pressure. What was your part?",
          "Tell me about a mistake you made and what you did about it.",
          "In simple terms, what is a bond, and why might its price fall when interest rates rise?",
        ),
        note: "Question count, timings and the technical question are from candidate and prep-site reports.",
      },
      NOT_REPLICATED("HackerRank assessment (Engineering only)", 3, "Engineering applicants take a HackerRank coding assessment. Other divisions skip this stage.", "Not replicated: practise coding problems on HackerRank itself."),
      {
        kind: "qa",
        name: "Superday: interviews",
        mode: "interview",
        stageOrder: 4,
        intro: "Goldman Sachs describes a Superday of two to five interviews. A degree apprentice reported three interviews of about 30 minutes covering their CV, experience and a reasoning question. This mock asks a selection.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: [
          ...prompts(
            "Walk me through your CV and tell me which experience taught you the most.",
            "When was the last time you showed teamwork skills?",
            "What does partnership mean to you, and when have you shown it?",
            "Tell me about a time you went out of your way to help someone you were serving, such as a customer or a club member.",
          ),
          { text: MARKETS_STORY },
        ],
      },
      {
        kind: "qa",
        name: "Superday: reasoning question",
        mode: "exercise",
        stageOrder: 4,
        intro: "Candidates report a logical reasoning question in the Superday. Interviewers care more about how you reason out loud than the final number.",
        prepSeconds: 60,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(GS_REASONING),
        note: "The real reasoning questions vary and are not published; this is an original estimation question.",
      },
    ],
  },
  {
    firm: "jp-morgan",
    title: "J.P. Morgan mock process",
    confidence: "multiple-candidate-reports",
    framework: {
      name: "J.P. Morgan's business principles",
      items: ["Exceptional client service", "Operational excellence", "Integrity, fairness and responsibility", "A great team and winning culture"],
    },
    notes: [
      "Based on 2024-25 candidate reports for the Financial Services degree apprenticeship: a written application, sometimes a phone screen, a virtual Superday of two 30-minute interviews, then an in-person assessment evening. J.P. Morgan bans AI tools during the Superday.",
    ],
    stages: [
      {
        kind: "qa",
        name: "Online application: written questions",
        mode: "exercise",
        stageOrder: 1,
        intro: "Applicants in the 2024 cycle answered two questions of up to 500 words alongside their CV. Write your answer as you would in the form.",
        prepSeconds: 0,
        answerSeconds: 900,
        retakes: 0,
        prompts: prompts(
          "What one trait makes you a unique candidate? (up to 500 words)",
          "How does a place on this programme support your career objectives? (up to 500 words)",
        ),
        note: "The questions may change each year.",
      },
      {
        kind: "qa",
        name: "Telephone screen (some locations)",
        mode: "interview",
        stageOrder: 2,
        intro: "Bournemouth applicants in 2024 reported a short telephone interview; 2025 London Finance applicants went straight to the Superday. Practise in case you get one.",
        prepSeconds: 0,
        answerSeconds: 120,
        retakes: 0,
        prompts: prompts(
          "Tell me about yourself in under two minutes.",
          "Why J.P. Morgan, and why an apprenticeship rather than university?",
        ),
        note: "A phone screen is a single report for one location.",
      },
      {
        kind: "qa",
        name: "Superday interview 1: motivation and competencies",
        mode: "interview",
        stageOrder: 3,
        intro: "The first of two 30-minute virtual interviews with different interviewers. Prepare two stories per competency, because each interviewer asks different questions.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(
          "What motivates you about this programme?",
          "Tell me about a time you had to keep high standards when you were short of time.",
          "Tell me about a time you worked with someone very different from you.",
          "Tell me about a time you took the lead without being asked.",
        ),
      },
      {
        kind: "qa",
        name: "Superday interview 2: competencies and technical",
        mode: "interview",
        stageOrder: 3,
        intro: "The second interview mixes competency questions with some technical and commercial questions, pitched at school-leaver level.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: [
          ...prompts(
            "What do you think an apprentice in operations or finance at J.P. Morgan does day to day?",
            "How might a rise in interest rates affect a bank and its clients?",
            "A client's payment has not arrived and they are upset. What would you do?",
            "Tell me about a time you noticed something was wrong and spoke up.",
          ),
        ],
      },
      {
        kind: "qa",
        name: "Assessment evening: networking introduction",
        mode: "interview",
        stageOrder: 4,
        intro: "The in-person assessment evening includes a networking part with apprentices and managers. Treat it as assessed.",
        prepSeconds: 30,
        answerSeconds: 60,
        retakes: 0,
        prompts: prompts(PITCH_60),
      },
      NOT_REPLICATED("Assessment evening: group task", 4, "Candidates describe a group task at the assessment evening, with supportive groups. Involve others, keep track of time and help the group reach a conclusion.", "Group tasks cannot be simulated alone; the format is a single report."),
    ],
  },
  {
    firm: "morgan-stanley",
    title: "Morgan Stanley mock process",
    confidence: "multiple-candidate-reports",
    framework: framework("morgan-stanley", "Morgan Stanley's core values", 5),
    notes: [
      "Morgan Stanley's apprentice process is not documented in detail. This mock follows reports from its campus (internship and graduate) process: application, Aon-style tests, HireVue, then interviews or an assessment centre. Apprentices may get a different set of stages.",
    ],
    stages: [
      APPLICATION(1, "Apply on Morgan Stanley's careers portal with your CV and often a cover letter. The portal limits how many programmes you can apply to each year.", [
        "Choose your programmes carefully because applications are capped.",
      ]),
      { kind: "test", name: "Online tests: numerical reasoning", testId: "scales-numerical", stageOrder: 2, note: "Aon (cut-e) tests are reported for campus roles, not confirmed for apprentices. This uses an Aon-style statement format." },
      { kind: "test", name: "Online tests: deductive reasoning", testId: "shl-deductive", stageOrder: 2, note: "Stands in for the reported logical reasoning test." },
      { kind: "test", name: "Online tests: situational judgement", testId: "sjt-most-least", stageOrder: 2, note: "Campus candidates report a chat-style situational judgement test; this replica uses written scenarios." },
      { kind: "test", name: "Online tests: switchChallenge", testId: "switch-challenge", stageOrder: 2, note: "Campus candidates report Aon's switchChallenge; this is a simplified, non-animated version. Reported for campus roles only." },
      {
        kind: "qa",
        name: "HireVue video interview",
        mode: "video",
        stageOrder: 3,
        intro: "Campus candidates report 3 to 5 behavioural and motivational questions, about 30 seconds to prepare and about 1.5 minutes to answer.",
        prepSeconds: 30,
        answerSeconds: 90,
        retakes: 0,
        prompts: reported("morgan-stanley", /HireVue/, 5),
        note: "Questions and timings are from campus reports, not apprentice-specific ones.",
      },
      {
        kind: "qa",
        name: "Assessment centre: case study",
        mode: "exercise",
        stageOrder: 4,
        intro: "Campus candidates report a case study at the assessment centre. Read the data, prepare, then present your recommendation.",
        prepSeconds: 600,
        answerSeconds: 300,
        retakes: 0,
        prompts: [{ text: SETTLEMENT_CASE.brief, stimulus: SETTLEMENT_CASE.stimulus }],
        note: "The real case content is not published; this is an original operations case.",
      },
      NOT_REPLICATED("Assessment centre: group exercise", 4, "Campus candidates report a group exercise. Listen, build on others' ideas and help the group decide.", "Group exercises cannot be simulated alone; reported for campus roles."),
      {
        kind: "qa",
        name: "Assessment centre: interview",
        mode: "interview",
        stageOrder: 4,
        intro: "A final interview on motivation, experience and Morgan Stanley's values.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(
          "Morgan Stanley's first core value is 'Do the right thing'. Tell me about a time you did.",
          "What do you know about how Morgan Stanley makes money, and which part interests you most?",
          "Tell me about a time you put someone else's needs first.",
          "Tell me about an idea you had that improved how something was done.",
        ),
      },
    ],
  },
  {
    firm: "bank-of-america",
    title: "Bank of America mock process",
    confidence: "multiple-candidate-reports",
    framework: framework("bank-of-america", "Bank of America's values", 4),
    notes: [
      "Based on candidate reports: an application with competency questions, a HireVue with 30 seconds to prepare and up to 3 minutes to answer, then an assessment centre with a competency interview and a technical or role interview.",
    ],
    stages: [
      APPLICATION(1, "An online application with your CV and competency questions. Recruiting is rolling and assessments start before the deadline.", [
        "Apply early: places can fill before the closing date.",
        "Check the GCSE requirement (Global Markets asked for Maths grade 7).",
      ]),
      {
        kind: "qa",
        name: "HireVue video interview",
        mode: "video",
        stageOrder: 2,
        intro: "Candidates report about 30 seconds to prepare and up to 3 minutes to answer, with 3 to 5 questions. Bank of America offers practice questions before the real ones.",
        prepSeconds: 30,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(
          "Why Bank of America, and why this programme?",
          "Tell me about a time you delivered something together with others.",
          "Tell me about a time you acted responsibly when it would have been easier not to.",
          "Tell me about a time you had to learn something difficult quickly.",
        ),
        note: "Question count is from candidate reports.",
      },
      {
        kind: "qa",
        name: "Assessment centre: competency interview",
        mode: "interview",
        stageOrder: 3,
        intro: "Reported as one of two interviews at the assessment centre.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(
          "Tell me about a time you had to trust someone else to do their part.",
          "Tell me about a time you helped someone else succeed.",
          "Describe a time you had to manage several deadlines at once.",
        ),
        note: "Single report.",
      },
      {
        kind: "qa",
        name: "Assessment centre: technical and role interview",
        mode: "interview",
        stageOrder: 3,
        intro: "The second interview is about the role. For Global Markets, expect questions on what sales and trading desks do and on recent markets news.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: [
          ...prompts(
            "What do you think the sales and trading desks do, and how would an apprentice help them?",
            "Bank of America talks about 'Responsible Growth'. What do you think it means?",
          ),
          { text: MARKETS_STORY },
        ],
        note: "Single report; questions are original.",
      },
    ],
  },
  {
    firm: "hsbc",
    title: "HSBC UK mock process",
    confidence: "multiple-candidate-reports",
    framework: framework("hsbc", "HSBC's values", 4),
    notes: [
      "HSBC's guide confirms an application, then an immersive online assessment with video answers, emails and data. Banking candidates in 2025 reported three final interviews and no assessment centre. Digital routes add a coding test and a virtual experience day.",
    ],
    stages: [
      APPLICATION(1, "About 10 to 15 minutes: eligibility questions and possibly a CV. Applicants report one application per cycle.", [
        "Pick your division deliberately: Commercial Banking, Wealth or Digital.",
      ]),
      { kind: "test", name: "Simulate: a day in the job", testId: "job-sim-banking", stageOrder: 2, note: "HSBC's Simulate assessment (built with Cappfinity) is a fictional working day with emails, data and ranked responses. This replica uses an original commercial-banking inbox; the real one also uses videos." },
      { kind: "test", name: "Simulate: data interpretation", testId: "capp-numerical", stageOrder: 2, note: "Prep sites describe data-monitoring tasks with tables and graphs in HSBC's Cappfinity simulation; this uses a Cappfinity-style, time-recorded replica." },
      {
        kind: "qa",
        name: "Simulate: recorded video responses",
        mode: "video",
        stageOrder: 2,
        intro: "Inside the simulation you record short video answers to work situations. Candidates report about 2 minutes to prepare and 2 minutes to answer, without re-recording.",
        prepSeconds: 120,
        answerSeconds: 120,
        retakes: 0,
        prompts: prompts(
          "You are on a project kick-off call and two colleagues disagree about what to do first. What would you say to move things forward?",
          "A colleague from another country seems frustrated with how your team communicates. How would you handle it?",
          "You have promised a manager a report today, and a client now needs urgent help. Talk through what you would do.",
          "Tell us about a time you took responsibility for something that went wrong.",
        ),
        note: "Timings and question count are from candidate reports.",
      },
      {
        kind: "qa",
        name: "Simulate: email reply",
        mode: "exercise",
        stageOrder: 2,
        intro: "Some routes include writing an email reply inside the simulation.",
        prepSeconds: 0,
        answerSeconds: 600,
        retakes: 0,
        prompts: prompts(HSBC_EMAIL),
        note: "The real email task is not published; this is an original scenario.",
      },
      NOT_REPLICATED("Technical assessment (Digital routes only)", 3, "Digital Business Services applicants take a Codility coding test (reported as 3 questions in 100 minutes for data roles).", "Not replicated: practise on Codility itself."),
      {
        kind: "qa",
        name: "Final interviews",
        mode: "interview",
        stageOrder: 4,
        intro: "Banking candidates in 2025 reported three interviews on the final day, with fairly standard questions. Tie your answers to your division and HSBC's values.",
        prepSeconds: 0,
        answerSeconds: 180,
        retakes: 0,
        prompts: prompts(
          "Why HSBC, and why this division?",
          "Tell me about a time you valued someone's different point of view.",
          "Tell me about a time you succeeded as part of a team.",
          "Tell me about a time you got something done despite obstacles.",
          "HSBC is an international bank. How could events abroad affect UK business clients?",
        ),
        note: "The three-interview format is a single report; the official graduate guide describes an assessment centre.",
      },
      {
        kind: "qa",
        name: "Final interviews: short case",
        mode: "exercise",
        stageOrder: 4,
        intro: "In case your final day includes a practical exercise (HSBC's graduate guide mentions them), practise a short data case.",
        prepSeconds: 480,
        answerSeconds: 240,
        retakes: 0,
        prompts: [{ text: RETAIL_BANK_CASE.brief, stimulus: RETAIL_BANK_CASE.stimulus }],
        note: "Not reported for banking degree apprentices; included as optional practice.",
      },
    ],
  },
];

// Profiles that stay reachable by URL but are not a current programme (see lib/directory.ts).
const NO_AUTO_MOCK = new Set(["civil-service-fast-track"]);

/** The hand-built mock processes first, then one generated from the profile's own stages for every other researched firm. */
export const ALL_MOCKS: MockProcess[] = [
  ...MOCKS,
  ...FIRMS.filter((f) => !NO_AUTO_MOCK.has(f.slug) && !MOCKS.some((m) => m.firm === f.slug))
    .map((f) => autoMock(f))
    .filter((m): m is MockProcess => m !== null),
];

export const getMock = (firmSlug: string) => ALL_MOCKS.find((m) => m.firm === firmSlug);

