// Job simulations: a working day told through an inbox, mixing response types (rank, choose, most/least, rate each,
// type a number, write a reply), as prep sites describe for Cappfinity simulations at HSBC, Deloitte, KPMG and EY.
// Hand-written and original; the firms and people are invented.

import type { Item, Stimulus } from "@/lib/assess/types";

type Sim = { stimuli: Record<string, Stimulus>; items: Item[] };

const email = (from: string, subject: string, time: string, body: string, table?: { columns: string[]; rows: (string | number)[][] }): Stimulus => ({
  type: "email",
  from,
  subject,
  time,
  body,
  ...(table ? { table } : {}),
});

export const BANKING_SIM: Sim = {
  stimuli: {
    "bk-1": email(
      "Sam Patel, Relationship Manager",
      "Today's priorities",
      "09:00",
      "Morning! Four things for today:\n(a) Prepare the pack for Harlow Joinery's 2pm review meeting.\n(b) The onboarding team need two missing documents for a new client by 11am, so the account can open today.\n(c) Update the team pipeline spreadsheet (due Friday).\n(d) Book a room for next week's team lunch.\nThanks, Sam",
    ),
    "bk-2": email(
      "Dana Harlow, Harlow Joinery",
      "Payment to our supplier",
      "09:25",
      "Hi, our payment to our timber supplier hasn't arrived and they're threatening to pause deliveries tomorrow. We're really worried. Can you help? Dana",
    ),
    "bk-3": email(
      "Finance team",
      "Quarterly lending figures",
      "10:05",
      "Here are the commercial lending balances for the first two quarters, as requested.",
      { columns: ["Segment", "Q1 (£ million)", "Q2 (£ million)"], rows: [["Small business", 120, 132], ["Mid-market", 300, 309], ["Total", 420, 441]] },
    ),
    "bk-4": email("Jordan, colleague", "Quick favour", "10:40", "Can you send me the Harlow Joinery file at my Gmail address? I want to finish the analysis at home tonight. Cheers!"),
    "bk-5": email(
      "Sam Patel, Relationship Manager",
      "Diary clash",
      "12:15",
      "Harlow have moved our meeting from 2pm to 3pm. Problem: I'm booked on compliance training at 3pm, and it's mandatory this week. Can you help sort this out?",
    ),
    "bk-6": email(
      "Sam Patel, Relationship Manager",
      "Reply to Dana, please",
      "13:00",
      "Good news: Dana's payment was held for a routine security check. It's now been released and should reach the supplier by 4pm today. Could you draft a short reply to her for me to send?",
    ),
    "bk-7": email("IT Service Desk <it-support@northfie1d-bank.co>", "URGENT: confirm your password", "14:20", "Your account will be locked in 1 hour. Reply with your username and password to keep access."),
    "bk-8": email("Calendar reminder", "End of day", "16:30", "Sam has left for the day. The pipeline spreadsheet (due Friday) isn't finished yet."),
  },
  items: [
    {
      id: "bk-rank",
      kind: "rank",
      stimulus: "bk-1",
      prompt: "Put Sam's four tasks in the order you should do them.",
      options: ["Prepare the Harlow Joinery pack for 2pm.", "Book a room for next week's team lunch.", "Send the onboarding team the missing documents by 11am.", "Update the pipeline spreadsheet (due Friday)."],
      order: [2, 0, 3, 1],
      orderLabel: "first thing first",
      explanation: "The 11am documents come first (earliest deadline, and a client's account depends on it), then the 2pm meeting pack, then Friday's spreadsheet, then the room booking.",
      difficulty: 2,
    },
    {
      id: "bk-client",
      kind: "most-least",
      stimulus: "bk-2",
      prompt: "How should you respond to Dana? Choose the most and least effective actions.",
      options: [
        "Forward the email to the payments team and leave it with them.",
        "Tell Dana the payment has gone through, so she can reassure her supplier, before you've checked.",
        "Reply to Dana promptly, check the payment's status with the payments team, and tell her when she'll hear back.",
        "Wait until Sam is out of his meeting at 12 before doing anything.",
      ],
      most: 2,
      least: 1,
      explanation: "Acknowledging quickly and owning the next step keeps the client's trust. Telling her it has gone through without checking could make things much worse.",
      difficulty: 2,
    },
    {
      id: "bk-growth",
      kind: "numeric",
      stimulus: "bk-3",
      prompt: "By what percentage did total lending grow from Q1 to Q2?",
      answer: 5,
      tolerance: 0.1,
      unit: "%",
      explanation: "(441 − 420) ÷ 420 × 100 = 5%.",
      difficulty: 2,
    },
    {
      id: "bk-segment",
      kind: "mcq",
      stimulus: "bk-3",
      prompt: "Which segment grew faster in percentage terms?",
      options: ["Mid-market", "Small business", "Both grew by the same percentage", "You cannot tell from the table"],
      answer: 1,
      explanation: "Small business grew by 12 ÷ 120 = 10%; mid-market by 9 ÷ 300 = 3%.",
      difficulty: 3,
    },
    {
      id: "bk-data",
      kind: "mcq",
      stimulus: "bk-4",
      prompt: "What is the best reply to Jordan?",
      options: [
        "Send it, since Jordan is a colleague.",
        "Send it, but remove the client's name first.",
        "Explain you can't send client files to a personal email address and suggest the bank's approved remote access.",
        "Ignore the message.",
      ],
      answer: 2,
      explanation: "Client information must stay on the bank's systems. A friendly explanation plus the approved alternative helps Jordan without breaking data rules.",
      difficulty: 1,
    },
    {
      id: "bk-clash",
      kind: "most-least",
      stimulus: "bk-5",
      prompt: "How should you help Sam? Choose the most and least effective actions.",
      options: [
        "Suggest Sam skips the training this once.",
        "Check whether the training has another slot this week and offer to propose a new meeting time to Harlow, then confirm with Sam.",
        "Move the client meeting to next week without asking Sam.",
        "Cancel Sam's training booking without telling anyone.",
      ],
      most: 1,
      least: 3,
      explanation: "Finding options and checking with Sam solves the clash properly. Cancelling mandatory compliance training behind his back is the worst choice.",
      difficulty: 3,
    },
    {
      id: "bk-reply",
      kind: "written",
      stimulus: "bk-6",
      prompt: "Write the reply to Dana for Sam to send (around 80 to 120 words).",
      checklist: [
        "Thanks Dana and acknowledges the worry the delay caused",
        "Explains simply that the payment was held for a routine security check",
        "Says it has now been released and should reach the supplier by 4pm today",
        "Says who to contact if it hasn't arrived",
        "Is short, polite and professional, with no jargon",
      ],
      minWords: 60,
      explanation:
        "Example: \"Hi Dana, thanks for your patience, and sorry for the worry this caused. Your payment was held for a routine security check, which we carry out to protect your account. It has now been released and should reach your supplier by 4pm today. If it hasn't arrived by then, please call me on my direct line and I'll chase it straight away. Kind regards, Sam\"",
      difficulty: 3,
    },
    {
      id: "bk-phish",
      kind: "rank",
      stimulus: "bk-7",
      prompt: "Rank these responses to the email from best to worst.",
      options: ["Forward it to colleagues to warn them.", "Report it with the phishing button or to IT security, without clicking anything.", "Reply with your password so you keep access.", "Delete it."],
      order: [1, 3, 0, 2],
      explanation: "The sender address is misspelt ('northfie1d') and real IT teams never ask for passwords. Reporting protects everyone; deleting protects only you; forwarding spreads the risky email; replying hands over your account.",
      difficulty: 2,
    },
    {
      id: "bk-eod",
      kind: "rate-each",
      stimulus: "bk-8",
      prompt: "Rate how effective each action would be.",
      actions: [
        "Mark the spreadsheet as finished in the team tracker.",
        "Note where you got to and plan to finish it first thing tomorrow, well before Friday.",
        "Stay until midnight to finish it tonight.",
        "Email Sam a short progress update.",
      ],
      ratings: [0, 3, 1, 2],
      explanation: "It isn't due until Friday, so planning tomorrow's work is best, and a short update keeps Sam informed. Working until midnight isn't needed, and marking unfinished work as done is dishonest.",
      difficulty: 2,
    },
  ],
};

export const AUDIT_SIM: Sim = {
  stimuli: {
    "au-1": email(
      "Aisha Khan, Audit Senior",
      "Plan for today: Brightwater Logistics audit",
      "08:45",
      "Morning! Today:\n(a) Request the missing bank statements from Brightwater's finance team; we need them by noon.\n(b) Test a sample of 10 sales invoices this afternoon.\n(c) Complete your timesheet for the week (due Friday).\n(d) Tidy up the shared audit folder.\nAisha",
    ),
    "au-2": email(
      "Lee Morgan, Finance Manager, Brightwater Logistics",
      "Bank statements",
      "09:30",
      "We've found the statements, but they include some personal details about staff expenses. Is it OK if we just send you a summary instead?",
    ),
    "au-3": email(
      "Aisha Khan, Audit Senior",
      "Invoice sample",
      "11:00",
      "Here are the first five invoices from your sample with the amounts recorded in the client's ledger. Please check them.",
      {
        columns: ["Invoice", "Invoice amount (£)", "Ledger amount (£)"],
        rows: [["INV-201", 4200, 4200], ["INV-202", 1850, 1580], ["INV-203", 960, 960], ["INV-204", 12400, 12400], ["INV-205", 3300, 3300]],
      },
    ),
    "au-4": email("Aisha Khan, Audit Senior", "Dinner invitation", "12:30", "Brightwater's finance director has offered to take the audit team out for a nice dinner tonight to say thank you."),
    "au-5": email("Aisha Khan, Audit Senior", "Your finding", "14:00", "Thanks for spotting the invoice difference. Please send me a short note explaining what you found and what you'd suggest doing next."),
    "au-6": email("Ben, fellow apprentice", "Help!", "15:15", "I'm really behind. Could you sign off my invoice testing as reviewed? I'll do the actual review next week, promise."),
    "au-7": email("Your working papers", "Check before you finish", "16:00", "Your plan said 10 invoices, but you have only tested 9."),
  },
  items: [
    {
      id: "au-rank",
      kind: "rank",
      stimulus: "au-1",
      prompt: "Put Aisha's four tasks in the order you should do them.",
      options: ["Test a sample of 10 sales invoices.", "Tidy up the shared audit folder.", "Request the missing bank statements by noon.", "Complete your timesheet (due Friday)."],
      order: [2, 0, 3, 1],
      orderLabel: "first thing first",
      explanation: "The statements are needed by noon and depend on the client replying, so request them first. Then the invoice testing planned for today, then Friday's timesheet, then the folder.",
      difficulty: 2,
    },
    {
      id: "au-evidence",
      kind: "mcq",
      stimulus: "au-2",
      prompt: "What is the best reply to Lee?",
      options: [
        "Accept the summary to save everyone time.",
        "Thank Lee, explain the audit needs the full statements as evidence, and check with Aisha how to receive them securely.",
        "Ask Lee to send everything by ordinary email straight away.",
        "Say you'll think about it and leave it.",
      ],
      answer: 1,
      explanation: "Auditors need original evidence, not a summary, and personal data must be transferred securely. Checking the secure route with your senior covers both.",
      difficulty: 2,
    },
    {
      id: "au-mismatch",
      kind: "mcq",
      stimulus: "au-3",
      prompt: "Which invoice does not match the ledger?",
      options: ["INV-201", "INV-202", "INV-204", "INV-205"],
      answer: 1,
      explanation: "INV-202 is £1,850 on the invoice but £1,580 in the ledger. The others match.",
      difficulty: 1,
    },
    {
      id: "au-diff",
      kind: "numeric",
      stimulus: "au-3",
      prompt: "By how much is the ledger amount lower than the invoice for that invoice?",
      answer: 270,
      unit: "£",
      explanation: "£1,850 − £1,580 = £270.",
      difficulty: 1,
    },
    {
      id: "au-dinner",
      kind: "most-least",
      stimulus: "au-4",
      prompt: "How should you respond? Choose the most and least effective actions.",
      options: [
        "Accept straight away and bring a friend.",
        "Decline rudely, saying it looks like a bribe.",
        "Accept, but go on your own without telling Aisha.",
        "Thank them and check with Aisha whether accepting fits the firm's independence rules.",
      ],
      most: 3,
      least: 0,
      explanation: "Auditors must stay independent of clients, so hospitality is checked against the firm's rules first. Accepting eagerly and bringing a guest is the worst look; declining rudely damages the relationship.",
      difficulty: 3,
    },
    {
      id: "au-note",
      kind: "written",
      stimulus: "au-5",
      prompt: "Write your note to Aisha (around 60 to 100 words).",
      checklist: [
        "Names the invoice and both amounts (invoice £1,850, ledger £1,580)",
        "States the difference of £270",
        "Doesn't guess the cause or accuse anyone",
        "Suggests a next step, such as asking the client for supporting documents",
        "Is clear and concise",
      ],
      minWords: 40,
      explanation:
        "Example: \"Hi Aisha, in my invoice sample, INV-202 is £1,850 on the invoice but recorded as £1,580 in the ledger, a difference of £270. The other four invoices match. I haven't found the reason yet. I suggest we ask Brightwater for the supporting documents (order and delivery note) and any credit notes for this invoice. Happy to draft the request. Thanks\"",
      difficulty: 3,
    },
    {
      id: "au-signoff",
      kind: "mcq",
      stimulus: "au-6",
      prompt: "What is the best reply to Ben?",
      options: [
        "Sign it off to help him out.",
        "Explain you can't sign off work you haven't reviewed, and offer to help him catch up or raise the time pressure with Aisha.",
        "Sign it off but add a private note saying you didn't review it.",
        "Tell the client that Ben is behind.",
      ],
      answer: 1,
      explanation: "Signing off work as reviewed when it wasn't is a serious breach of audit quality and honesty. Helping Ben, or raising the workload, solves the real problem.",
      difficulty: 1,
    },
    {
      id: "au-sample",
      kind: "rate-each",
      stimulus: "au-7",
      prompt: "Rate how effective each action would be.",
      actions: ["Change the plan to say 9 so it matches.", "Test the 10th invoice and update your working papers.", "Leave it: 9 is close enough.", "Tell Aisha and ask whether 9 is acceptable."],
      ratings: [0, 3, 1, 2],
      explanation: "Completing the planned sample is best; asking your senior is reasonable. Leaving it undermines the audit, and changing the plan to hide the gap is the worst choice.",
      difficulty: 2,
    },
  ],
};
